version: 2
updates:
  - package-ecosystem: "docker-compose"
    open-pull-requests-limit: 15
    schedule:
      interval: weekly
    directories:
      - "/docker/gitea-actions"
      - "/docker/home/esphome"
      - "/docker/home/matter-server"
      - "/docker/home/mosquitto-mqtt"
      - "/docker/home/n8n"
      - "/docker/home/node-red"
      - "/docker/home/zigbee2mqtt"
      - "/docker/infrastructure/mail/roundcube"
      - "/docker/infrastructure/mail/stalwart"
      - "/docker/infrastructure/network/traefik"
      - "/docker/infrastructure/squid"
      - "/docker/infrastructure/sshportal"
      - "/docker/personal/gramps"
      - "/docker/personal/media/films-series/jackett"
      - "/docker/personal/media/films-series/jellyfin"
      - "/docker/personal/media/films-series/jellyseerr"
      - "/docker/personal/media/films-series/radarr"
      - "/docker/personal/media/films-series/sonarr"
      - "/docker/personal/media/films-series/transmission"
      - "/docker/personal/media/films-series/wizarr"
      - "/docker/personal/media/music/navidrome"
      - "/docker/personal/media/youtube/tubearchivist"
      - "/docker/personal/paperless"
      - "/docker/personal/radicale"
      - "/docker/personal/syncthing"
      - "/docker/personal/tandoor"
      - "/docker/production/alexscript"
      - "/docker/production/buildpath"
      - "/docker/production/semeryfr"
      - "/docker/production/vhaudiquetfr"
      - "/docker/tools/excalidraw"
      - "/docker/tools/obsidian-livesync"
      - "/docker/tools/stirling-pdf"
  - package-ecosystem: "helm"
    open-pull-requests-limit: 15
    schedule:
      interval: weekly
    directories:
      - "/kubernetes/code/gitea"
      - "/kubernetes/code/harbor"
      - "/kubernetes/home/home-assisant"
      - "/kubernetes/home/zigbee2mqtt"
      - "/kubernetes/infrastructure/authentik"
      - "/kubernetes/personal/linkwarden"
      - "/kubernetes/personal/notesnook"
      - "/kubernetes/personal/photoprism"
      - "/kubernetes/production/umami"
      - "/kubernetes/system/csi-driver-nfs"
      - "/kubernetes/system/external-dns"
      - "/kubernetes/system/traefik"
      - "/kubernetes/tools/dashy"
      - "/kubernetes/tools/glance"
