services:
  vhaudiquetfr:
    container_name: vhaudiquetfr
    image: git.vhaudiquet.fr/vhaudiquet/vhaudiquet.fr:b45805fa8e42448eb13ba81952f87feace294440
    networks:
      - default
      - proxy
    ports:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vhaudiquetfr.rule=Host(`vhaudiquet.fr`)"
    environment:
      - NGINX_HOST=vhaudiquet.fr
      - NGINX_PORT=80
    volumes:
      - files:/usr/share/nginx/html/files
      - public:/usr/share/nginx/html/public

networks:
  proxy:
    external: true
    name: proxy

volumes:
  files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/vhaudiquetfr/files'
  public:
    driver_opts:
      type: 'nfs'
      o: 'addr=truenas.lan'
      device: ':/mnt/main_storage/public'
