apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: umami
  namespace: umami
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: umami
        namespace: umami
      chart: umami
      version: '7.1.0'
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: umami-values
