persistence:
  enabled: true
ingress:
  enabled: true
  external: false
  hosts:
    - host: homeassistant-test.lan
      paths:
        - path: /
          pathType: Prefix
configurations:
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 127.0.0.0/8
