services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.2.6
    environment:
      - TZ=Europe/Paris
      - N8N_SECURE_COOKIE=false
      - NODES_EXCLUDE="[]"
    ports:
      - "5678"
    networks:
      - default
      - proxy
    volumes:
      - data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.lan`)"

  redis:
    image: redis:8.2.2

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app/n8n/data'

networks:
  proxy:
    external: true
    name: proxy
